const fs = require("fs");
const path = require("path");

const tokensPath = path.resolve(__dirname, "../svelte/src/tokens.json");
const outputDir = path.resolve(__dirname, "../svelte/src/generated");

const tokens = JSON.parse(fs.readFileSync(tokensPath, "utf8"));

function toKebabCase(value = "") {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[_\s]+/g, "-")
    .toLowerCase();
}

function flattenTokens(input, parent = []) {
  if (input && typeof input === "object" && !Array.isArray(input)) {
    return Object.entries(input).flatMap(([key, val]) =>
      flattenTokens(val, [...parent, key])
    );
  }
  return [
    {
      name: parent.map(toKebabCase).join("-"),
      value: input,
    },
  ];
}

const flatTokens = flattenTokens(tokens);

const cssLines = flatTokens
  .map(({ name, value }) => `  --${name}: ${value};`)
  .join("\n");

const cssOutput = `/* Generated by scripts/build-tokens.js. Do not edit directly. */
:root {
${cssLines}
}
`;

function buildThemeBlock(themeName, themeValues) {
  const flatTheme = flattenTokens(themeValues);
  const lines = flatTheme
    .map(({ name, value }) => `  --${name}: ${value};`)
    .join("\n");
  return `:root[data-theme="${themeName}"] {\n${lines}\n}\n`;
}

let themeCssOutput = "";
if (tokens.themes && typeof tokens.themes === "object") {
  Object.entries(tokens.themes).forEach(([themeName, themeValues]) => {
    themeCssOutput += buildThemeBlock(themeName, themeValues);
  });
}

const jsOutput = `// Generated by scripts/build-tokens.js. Do not edit directly.
const toKebabCase = (value = "") =>
  value
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[_\\s]+/g, "-")
    .toLowerCase();

export const tokens = ${JSON.stringify(tokens, null, 2)};

export function getToken(path) {
  return (path || "").split(".").reduce((acc, key) => {
    if (acc == null) return acc;
    return acc[key];
  }, tokens);
}

export function cssVar(path) {
  return \`var(--\${(path || "")
    .split(".")
    .map(toKebabCase)
    .join("-")})\`;
}
`;

fs.mkdirSync(outputDir, { recursive: true });
fs.writeFileSync(
  path.join(outputDir, "tokens.css"),
  themeCssOutput ? `${cssOutput}\n${themeCssOutput}` : cssOutput
);
fs.writeFileSync(path.join(outputDir, "tokens.js"), jsOutput);

console.log("Generated tokens CSS and JS.");
